FROM nginx

# Copy nginx configuration
COPY app/nginx/nginx.conf /etc/nginx/nginx.conf

# Copy frontend bundle to nginx web root
COPY frontend/dist /usr/share/nginx/html

EXPOSE 4000

CMD ["nginx", "-g", "daemon off;"]