spring.application.name=pokerDice
spring.main.allow-bean-definition-overriding=true
spring.profiles.active=jdbc
server.port=${port:8080}
logging.level.pt.isel.daw=DEBUG
spring.jackson.property-naming-strategy=SNAKE_CASE